apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: opportunistic-priority
value: 0
globalDefault: false
description: "This priority class should be used for opportunistic service pods only."
