apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrent-app4
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        slo: "0.5"
        controller: "concurrent-app4"
        qosMeasuring: "concurrent"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: 200Mi
              cpu: 1.7
            limits:
              memory: 200Mi
              cpu: 1.7
