apiVersion: apps/v1
kind: Deployment
metadata:
  name: independent-app1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        slo: "0.5"
        controller: "independent-app1"
        qosMeasuring: "independent"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: 200Mi
              cpu: 1.7
            limits:
              memory: 200Mi
              cpu: 1.7
